### ISSUE TITLE
ImportError: No module named models

### ISSUE THREAD

**Issue by tomsbergmanis** [ZurichNLP/coling2018-neural-transition-based-morphology#1]
Hi, 
I would really like to compare my model against yours :) Would it be possible to get some support to set-up your code-base? 
I was trying to run your code, but with the set-up instructions you have provided I ended up getting this:

`cd lib && python launch_dataset.py ../dataset_configs/sgm2017medium_config.py > sgm2017medium.sh ; bash -x sgm2017medium.sh
Traceback (most recent call last):
  File "launch_dataset.py", line 439, in <module>
    main()
  File "launch_dataset.py", line 431, in main
    raise e
ImportError: No module named models
 ../dataset_configs/sgm2017medium_config.py
`
Thanks,
Toms Bergmanis

**Comment by gozdesahin** [comment]
Hi,
I have the same issue, what's the solution :)

**Comment by simon-clematide** [comment]
The lines with `import models` should just be deleted. It is a left-over from another version. I'll fix it right now.
